### ISSUE TITLE
openstack原生接口冲突

### ISSUE THREAD

**Issue by baolinCloud** [Huawei/OpenStackClient_CES#6]
https://docs.openstack.org/python-openstackclient/latest/cli/command-objects/quota.html

quota
  
UPDATED: 2017-09-13 19:38
Resource quotas appear in multiple APIs, OpenStackClient presents them as a single object with multiple properties.

Block Storage v1, v2, Compute v2, Network v2

quota list¶
List quotas for all projects with non-default quota values

openstack quota list
    --compute | --network | --volume
--network¶
List network quotas

--compute¶
List compute quotas

--volume¶
List volume quotas

**Comment by IamFive** [comment]
quota list 是项目完成后，官方才加的命令。你不要用最新版的openstackclient就不会有这个问题。我记得项目交付的时候，有确认openstackclient的版本的（我没记错的话，是3.9.0）。

**Comment by IamFive** [comment]
确认完了给我个回复哈，这个不是项目的bug。

**Comment by baolinCloud** [comment]
好的，是否需要在wiki里说明支持版本？

**Comment by IamFive** [comment]
这个版本文档是你们内部出给用户的。上次说好像是用 2.4/2.5
